### PR TITLE
Fetch values for components

### LINKED ISSUE #20: Ability to query all possible values of a dimension
Thank you for this library, it 's extremely useful!

Currently, I can easily retrieve the dimensions of a datacube with `datacube.dimensions()`. Would it be possible to also retrieve all the possible values that a dimension can have? For instance all the spatial units that a spatial dimension can have. 

A SPARQL query would look something like this I think:
```
SELECT DISTINCT ?value WHERE {
      ?obs a qb:Observation;
        <dimension>/rdfs:label ?value .
    }
```

The goal is to then query the observations with a filter value like this:
```
datacube
  .query()
  .filter(dimension.equals(dimensionValue))
```

### PR DESCRIPTION
**Pull request by vhf**
Fixes #20 

TODO:
- [x] fetch distinct values
- [x] fetch min/max values
- [x] ~~try to be smart about it~~
- [x] tests
- [ ] jsdoc/typedoc
- [ ] doc

### CODE REVIEW

**Comment by vhf** [comment]
> Sure, I could implement it on Dimension/Attribute/Measure and we'd use it like this:
> 
> ```js
> myDimension.values()
> ```
> [*source*](https://github.com/zazuko/query-rdf-data-cube/issues/20#issuecomment-530755620)

Turns out values depend on the data cube so I came up with a different API:

https://github.com/zazuko/query-rdf-data-cube/blob/cefd4e576f7030abdc07c16687f82fbf7d7519d3/examples/component-values.ts#L14-L45

https://github.com/zazuko/query-rdf-data-cube/blob/cefd4e576f7030abdc07c16687f82fbf7d7519d3/examples/component-values-min-max.ts#L10-L29

Could you please comment on that @ktk @herrstucki @lucguillemot?

**Comment by herrstucki** [comment]
Awesome, looks good to me!

I wonder if additionally adding the possibility to add this to queries as well would be possible (like i described in https://github.com/zazuko/query-rdf-data-cube/issues/20#issuecomment-530817209):

```js
// All dimension values of a cube
await cube.componentValues(myDimension) // => [1,2,3,4,5]

// Construct query without executing
const query = cube.query().filter(something)

// All dimension values of this query
await query.componentValues(myDimension) // => [3,5]
```

**Comment by vhf** [comment]
Sounds like something useful, I'll try to implement it and come back to you for feedback on the API, it might diverge a bit from your example.

**Comment by ktk** [comment]
@vhf lgtm, if it's useful for IXT I'm good :)

**Pull request merged**
